default_stages: [commit]
fail_fast: false
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks.git
      rev: v4.3.0
      hooks:
          - id: trailing-whitespace
          - id: check-merge-conflict
          - id: end-of-file-fixer
          - id: debug-statements
          - id: check-ast
    -   repo: https://github.com/PyCQA/autoflake
        rev: v2.0.0
        hooks:
          - id: autoflake
            args: [--in-place, --remove-all-unused-imports]
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            name: isort (python)
            args: [--multi-line, VERTICAL_HANGING_INDENT, --trailing-comma]
    - repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
          - id: black
            language_version: python3
            args: [--config=black.toml]
    - repo: https://github.com/RobertCraigie/pyright-python
      rev: v1.1.376
      hooks:
      - id: pyright
