# syntax=docker/dockerfile:1

FROM python:3.10-slim-bullseye

# LABEL Jeff Navarra "jeff.navarra@miapeer.com"

# Install stuff
RUN apt-get update \
    && apt-get install -y curl gnupg \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && apt-get install -y gcc g++ unixodbc-dev \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql17

# Clean up
RUN rm -rf /var/lib/apt/lists/*
# RUN apk del py-pip
# RUN apk del gcc g++ unixodbc-dev

COPY ./requirements.txt /miapeer/requirements.txt

WORKDIR /miapeer

RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
