# syntax=docker/dockerfile:1

FROM --platform=linux/amd64 python:3.10-slim-bullseye

# LABEL Jeff Navarra "jeff.navarra@miapeer.com"

# Install stuff
RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y gnupg
RUN curl https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc
RUN curl https://packages.microsoft.com/config/debian/11/prod.list | tee /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update
RUN apt-get install -y gcc
RUN apt-get install -y g++
RUN apt-get install -y unixodbc-dev
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql18

# Clean up
RUN rm -rf /var/lib/apt/lists/*
# RUN apk del py-pip
# RUN apk del gcc g++ unixodbc-dev

COPY ./requirements.txt /miapeer/requirements.txt

WORKDIR /miapeer

RUN pip install --no-cache-dir -r requirements.txt

COPY . /miapeer

# TODO: Set for proper prod deployment

EXPOSE 80

RUN date +%Y.%m.%d-%H:%M:%S > last_update

CMD ["./start_server"]
