# syntax=docker/dockerfile:1

FROM python:3.10-slim-bullseye

# LABEL Jeff Navarra "youremail@domain.tld"

COPY ./requirements.txt /miapeer/requirements.txt

WORKDIR /miapeer

# Install stuff
RUN apt-get update \
    && apt-get install -y curl gnupg \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && apt-get install -y gcc g++ unixodbc-dev \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql17 \
    && pip install --no-cache-dir -r requirements.txt \

    # Clean up
    && rm -rf /var/lib/apt/lists/*

# Uninstall stuff
# RUN apk del py-pip
# RUN apk del gcc g++ unixodbc-dev

# RUN mkdir /api

# Environment vars
# ENV PATH "$PATH:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ENV FLASK_APP app.py
ENV FLASK_ENV=development
ENV FLASK_RUN_HOST 0.0.0.0

EXPOSE 5000
# EXPOSE 8000

# CMD [ "sh" ]

# ENTRYPOINT [ "python" ]
# CMD [ "app.py" ]

# CMD [ "python", "app.py" ]

CMD [ "python", "-m", "flask", "run" ]

# CMD [ "gunicorn", "-w", "4", "-b", ":8000", "app:app" ]
