FROM python:3.14-slim

# Install stuff
RUN apt-get update
RUN apt-get install -y curl
# RUN apt-get install -y gnupg
RUN curl https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc
RUN curl https://packages.microsoft.com/config/debian/11/prod.list | tee /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update
# RUN apt-get install -y gcc
# RUN apt-get install -y g++
# RUN apt-get install -y unixodbc-dev
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql18

# Dev setup
RUN apt-get install -y sqlite3
RUN apt-get install -y git
RUN pip install pipx && pipx ensurepath
ENV PATH="/root/.local/bin:$PATH"
# RUN curl -LsSf https://astral.sh/uv/install.sh | sh
RUN pipx install go-task-bin
RUN pipx install uv
RUN uv tool install prek

# Clean up
RUN rm -rf /var/lib/apt/lists/*

# COPY ./requirements.txt /miapeer/requirements.txt

WORKDIR /workspaces/api

# RUN pip install --no-cache-dir -r requirements.txt
# RUN uv pip install -r requirements.txt

EXPOSE 8000

CMD ["fastapi", "dev", "miapeer/app.py"]
