# syntax=docker/dockerfile:1

FROM python:3.10-slim-bullseye

COPY ./requirements.txt /miapeer/requirements.txt

WORKDIR /miapeer

# Install stuff
RUN apt-get update \
    # && apt-get install -y software-properties-common \
    # && add-apt-repository ppa:git-core/ppa \
    # && apt-get update \
    && apt-get install -y curl gnupg \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && apt-get install -y gcc g++ unixodbc-dev \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql17 \
    && pip install --no-cache-dir -r requirements.txt \

    # Clean up
    && rm -rf /var/lib/apt/lists/*

COPY . /miapeer

# Environment vars

EXPOSE 8000

CMD [ "gunicorn", "-w", "4", "-b", ":8000", "app:app" ]
