version: '3'

silent: true

dotenv: ['.env']

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all

  compile-requirements:
    cmds:
      - pip-compile

  start:
    cmds:
      - ./start_server

  tdd:
    cmds:
      - ptw

  coverage-report:
    cmds:
      - pytest --cov-report term-missing:skip-covered --cov=miapeer miapeer/tests/

  type-check:
    cmds:
      - pyright -w
