version: '3'

dotenv: ['.env']

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all

  compile-requirements:
    cmds:
      - pip-compile

  start:
    cmds:
      - ./start_server

  tdd:
    dir: '{{.WORKDIR}}'
    cmds:
      - ptw --runner "bash pytest-runner.sh" --ext .py,.sql

  coverage-report:
    aliases: [cov, coverage]
    cmds:
      - pytest --cov=miapeer --cov-report=term-missing:skip-covered --cov-fail-under=90 miapeer/tests/

  type-check:
    aliases: [ty]
    dir: '{{.WORKDIR}}'
    cmds:
      - uvx ty check --watch
